name: Build and Push image 
on:
  push:
    branches:
    - 'main'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Trivy vulnerability scanner in repo mode
        id: scan_vulnerability
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          output: 'trivy-results.txt'
          severity: 'CRITICAL'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "1143274832@qq.com"
          password: "duhaoxi010909."

      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          push: true
          tags: garden1a/go-fortune:${{ github.sha }}
   
      - name: Digitally sign the image
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: garden1a/go-fortune:${{ github.sha }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "test-submission"
          SLACK_COLOR: "success"
          SLACK_MESSAGE: "Name: Du Haoxi \n Email:E1327905@u.nus.edu \n Git:https://github.com/Gardeni1a/go-fortune \n Image:https://hub.docker.com/repository/docker/garden1a/go-fortune"
          SLACK_USERNAME: "Du Haoxi"
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
