name: Build and Push
on:
  push:
    branches:
    - 'release/v1.0'
jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Run Trivy vulnerability scanner in repo mode
        id: scan_vulnerability
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'

      - name: Slack Notification when trivy fails
        if: success() && job.steps.scan_vulnerability.status == failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "submission"
          SLACK_COLOR: "failure"
          SLACK_MESSAGE: "Failed trivy scan, see below report"
          SLACK_TITLE: "Scan failed"
          SLACK_USERNAME: "Du Haoxi"
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

      - name: upload the trivy report
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: "xoxb-6957628588181-7028297010820-T9Ltevs8E59VkmCYZzrORrJi"
          channel_id: "C06U8J674SE"
          file_path: '${{ github.workspace }}/trivy-results.txt'
          initial_comment: 'upload the trivy report'
